routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Admin Route
Route::resource('shopkeeper', 'ShopkeeperController')->middleware('auth');
Route::get('shopkeeper/{shopkeeper}/delete', 'ShopkeeperController@destroy')->name('shopkeeper.delete');
Route::resource('loyaltyprogram', 'LoyaltyProgramController')->middleware('auth');
Route::get('loyaltyprogram/{loyaltyprogram}/delete', 'LoyaltyProgramController@destroy')->name('loyaltyprogram.delete');
Route::resource('item', 'ItemController')->middleware('auth');
Route::get('item/{item}/delete', 'ItemController@destroy')->name('item.delete');
Route::resource('shopkeeperstatus', 'ShopkeeperStatusController')->middleware('auth');
Route::resource('customer', 'CustomerController')->middleware('auth');
Route::resource('useraccess', 'UserAccessController')->middleware('auth');
Route::resource('accesslog', 'AccessLogController')->middleware('auth');

//Staff Route
Route::resource('order', 'OrderController')->middleware('auth');
Route::get('order/{order}/delete', 'OrderController@destroy')->name('order.delete');
Route::resource('bill', 'BillController')->middleware('auth');
Route::post('printreceipt', 'BillController@checkout')->middleware('auth')->name('bill.checkout');

//Management Route
Route::get('financereport', 'FinanceReportController@index')->middleware('auth')->name('financereport.index');
Route::get('financereport/printreport', 'FinanceReportController@printreport')->middleware('auth')->name('financereport.printreport');
Route::get('financereport/cash', 'FinanceReportDetailController@cashindex')->middleware('auth')->name('financereport.cashindex');
Route::get('financereport/debit', 'FinanceReportDetailController@debitindex')->middleware('auth')->name('financereport.debitindex');
Route::get('financereport/credit', 'FinanceReportDetailController@creditindex')->middleware('auth')->name('financereport.creditindex');
Route::get('financereport/cash/printreport', 'FinanceReportDetailController@printcashreport')->middleware('auth')->name('financereport.printcashreport');
Route::get('financereport/debit/printreport', 'FinanceReportDetailController@printdebitreport')->middleware('auth')->name('financereport.printdebitreport');
Route::get('financereport/credit/printreport', 'FinanceReportDetailController@printcreditreport')->middleware('auth')->name('financereport.printcreditreport');
Route::get('omzetreport', 'OmzetReportController@index')->middleware('auth')->name('omzetreport.index');
Route::get('omzetreport/detail/{time}', 'OmzetReportController@show')->middleware('auth')->name('omzetreport.show');
Route::get('omzetreport/printomzetreport', 'OmzetReportController@printomzetreport')->middleware('auth')->name('omzetreport.printomzetreport');
Route::get('omzetreport/detail/{time}/printreportdetail', 'OmzetReportController@printreportdetail')->middleware('auth')->name('omzetreport.printreportdetail');
Route::get('trendreport', 'TrendController@index')->middleware('auth')->name('trendreport.index');
Route::get('trendreport/{group}', 'TrendController@show')->middleware('auth')->name('trendreport.show');
Route::get('trendreport/{group}/printtrendreport', 'TrendController@printtrendreport')->middleware('auth')->name('trendreport.printtrendreport');
Route::get('customerreport', 'CustomerProfileController@index')->middleware('auth')->name('customerreport.index');
Route::get('customerreport/citysegmentreport', 'CustomerProfileController@reportcitysegment')->middleware('auth')->name('customerreport.citysegmentreport');
Route::get('customerreport/professionsegmentreport', 'CustomerProfileController@reportprofessionsegment')->middleware('auth')->name('customerreport.professionsegmentreport');
Route::get('customerreport/showgendersegment/{gender}', 'CustomerProfileDetailController@showgendersegment')->middleware('auth')->name('customerreport.showgendersegment');
Route::get('customerreport/showmaritalsegment/{marital}', 'CustomerProfileDetailController@showmaritalsegment')->middleware('auth')->name('customerreport.showmaritalsegment');
Route::get('customerreport/showagesegment/{age}', 'CustomerProfileDetailController@showagesegment')->middleware('auth')->name('customerreport.showagesegment');
Route::get('customerreport/showgendersegment/{gender}/reportgendersegment', 'CustomerProfileDetailController@reportgendersegment')->middleware('auth')->name('customerreport.reportgendersegment');
Route::get('customerreport/showmaritalsegment/{marital}/reportmaritalsegment', 'CustomerProfileDetailController@reportmaritalsegment')->middleware('auth')->name('customerreport.reportmaritalsegment');
Route::get('customerreport/showagesegment/{age}/reportagesegment', 'CustomerProfileDetailController@reportagesegment')->middleware('auth')->name('customerreport.reportagesegment');

//Upload Picture
Route::get('store/{store}', 'UploadPictureController@upload')->name('upload.picture');
Route::put('store/{store}', 'UploadPictureController@store')->name('store.picture');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    public function orders()
    {
        return $this->hasMany(Order::class, 'item_id');
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Validator;
use App\Item;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::latest('updated_at')->paginate(10);
        return view('item.index', ['items' => $items]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('item.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'item_name' => 'required',
            'price' => 'required|numeric',
            'description' => 'required',
            'stock' => 'required|numeric',
        ];
        $messages = [
            'item_name.required' => 'Nama Item harus diisi',
            'price.required' => 'Harga Item harus diisi',
            'description.required' => 'Deskripsi Item harus diisi',
            'stock.required' => 'Jumlah Item harus diisi',
            'price.numeric' => 'Harga Item harus berupa angka',
            'stock.numeric' => 'Jumlah Item harus berupa angka',
        ];
        Validator::make($request->all(), $rules, $messages)->validate();
        $item = new Item();
        $item->item_name = $request->item_name;
        $item->price = $request->price;
        $item->description = $request->description;
        $item->stock = $request->stock;
        $item->save();
        return redirect()->route('item.index')->with('message', 'Data berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        return view('item.view', ['item' => $item]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        return view('item.edit', ['item' => $item]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $rules = [
            'item_name' => 'required',
            'price' => 'required|numeric',
            'description' => 'required',
            'stock' => 'required|numeric',
        ];
        $messages = [
            'item_name.required' => 'Nama Item harus diisi',
            'price.required' => 'Harga Item harus diisi',
            'description.required' => 'Deskripsi Item harus diisi',
            'stock.required' => 'Jumlah Item harus diisi',
            'price.numeric' => 'Harga Item harus berupa angka',
            'stock.numeric' => 'Jumlah Item harus berupa angka',
        ];
        Validator::make($request->all(), $rules, $messages)->validate();
        $item->item_name = $request->get('item_name');
        $item->price = $request->get('price');
        $item->description = $request->get('description');
        $item->stock = $request->get('stock');
        $item->save();
        return redirect()->route('item.index')->with('message', 'Data berhasil diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();
        return redirect()->route('item.index')->with('message', 'Data berhasil dihapus');
    }
}

resources/views/item/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Tambah Barang</h3>
			@if ($errors->count() > 0)
			<div class="alert alert-danger">
				@foreach ($errors->all() as $message)
				    <li>{{ $message }}</li>
				@endforeach
			</div>
			@endif
			<form action="{{ route('item.store') }}" method="post">
				
				{{ csrf_field() }}

				<div class="form-group">
					<label>Nama Barang</label>
					<input type="text" name="item_name" class="form-control" value="{{ old('item_name') }}">
				</div>
				<div class="form-group">
					<label>Harga</label>
					<input type="number" name="price" min="0" class="form-control" value="{{ old('price') }}">
				</div>
				<div class="form-group">
					<label>Stok</label>
					<input type="number" name="stock" min="1" class="form-control" value="{{ old('stock') }}">
				</div>
				<div class="form-group">
					<label>Deskripsi Barang</label>
					<input type="textarea" name="description" class="form-control" value="{{ old('description') }}">
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
				<a class="btn btn-primary" href="{{ route('item.index') }}" role="button">Kembali</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/item/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Edit Data Barang</h3>
			<form action="{{ route('item.update', $item) }}" method="post">
				
				{{ csrf_field() }}
				{{ method_field('put') }}

				<div class="form-group">
					<label>Nama Barang</label>
					<input type="text" name="item_name" class="form-control" value="{{ $item->item_name}}">
				</div>
				<div class="form-group">
					<label>Harga</label>
					<input type="number" name="price" min="0" class="form-control" value="{{ $item->price}}">
				</div>
				<div class="form-group">
					<label>Stok</label>
					<input type="number" name="stock" min="1" class="form-control" value="{{ $item->stock}}">
				</div>
				<div class="form-group">
					<label>Deskripsi Barang</label>
					<input type="textarea" name="description" class="form-control" value="{{ $item->description}}">
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
				<a class="btn btn-primary" href="{{ route('item.index') }}" role="button">Kembali</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/item/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col">
			<h3>Daftar Barang</h3>
			@if(Session::has('message'))
				<div class="alert alert-success">{{ Session::get('message') }}</div>
			@endif
			<a href="{{ route('item.create') }}" class="btn btn-primary">Tambah Barang</a>
			<br></br>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Nomor</th>
						<th>Nama Barang</th>
						<th>Harga</th>
						<th>Stok</th>			
						<th>Aksi</th>
					</tr>
				</thead>
				<tbody>
					@forelse ($items as $item)
					<tr>
						<td>{{ $item->id }}</td>
						<td>{{ $item->item_name }}</td>
						<td>Rp {{ number_format($item->price, 2, ',', '.') }}</td>
						<td>{{ $item->stock }}</td>
						<td>
							<a href="{{ route('item.show', $item->id) }}" class="btn btn-warning">View</a>
							<a href="{{ route('upload.picture', $item->id) }}" class="btn btn-info">Upload</a>
							<a href="{{ route('item.edit', $item->id) }}" class="btn btn-primary">Edit</a>
							<a href="{{ route('item.delete', $item->id) }}" class="btn btn-danger">Delete</a>
						</td>
					</tr>
					@empty
					    <td colspan="5">Belum ada data</td>
					@endforelse
				</tbody>
			</table>
			{!! $items->links() !!}
		</div>
	</div>
</div>
@endsection

resources/views/item/upload.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Upload Gambar Barang</h3>
			<form action="{{ route('store.picture', $item->id) }}" enctype="multipart/form-data" method="post">
				
				{{ csrf_field() }}
				{{ method_field('put') }}

				<input type="file" name="image" class="custom-file-input">
				<br>
				<button type="submit" class="btn btn-primary">Upload</button>
				<a class="btn btn-primary" href="{{ route('item.index') }}" role="button">Kembali</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/item/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Detail Data Barang</h3>
				<div class="form-group">
					<div class="col-lg-3 control-label">Nama Barang</div>
					<div class="col-lg-9"> {{ $item->item_name}} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Harga</div>
					<div class="col-lg-9"> Rp {{ number_format($item->price, 2, ',', '.') }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Stok</div>
					<div class="col-lg-9"> {{ $item->stock}} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Deskripsi</div>
					<div class="col-lg-9"> {{ $item->description}} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Gambar</div>
					<div class="col-lg-9"> <img src="{{ asset($item->picture_url) }}" alt="No Picture"></div>
				</div>
				<br>
				<a class="btn btn-primary" href="{{ route('item.index') }}" role="button">Kembali</a>
		</div>
	</div>
</div>
@endsection