routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Admin Route
Route::resource('shopkeeper', 'ShopkeeperController')->middleware('auth');
Route::get('shopkeeper/{shopkeeper}/delete', 'ShopkeeperController@destroy')->name('shopkeeper.delete');
Route::resource('loyaltyprogram', 'LoyaltyProgramController')->middleware('auth');
Route::get('loyaltyprogram/{loyaltyprogram}/delete', 'LoyaltyProgramController@destroy')->name('loyaltyprogram.delete');
Route::resource('item', 'ItemController')->middleware('auth');
Route::get('item/{item}/delete', 'ItemController@destroy')->name('item.delete');
Route::resource('shopkeeperstatus', 'ShopkeeperStatusController')->middleware('auth');
Route::resource('customer', 'CustomerController')->middleware('auth');
Route::resource('useraccess', 'UserAccessController')->middleware('auth');
Route::resource('accesslog', 'AccessLogController')->middleware('auth');

//Staff Route
Route::resource('order', 'OrderController')->middleware('auth');
Route::get('order/{order}/delete', 'OrderController@destroy')->name('order.delete');
Route::resource('bill', 'BillController')->middleware('auth');
Route::post('printreceipt', 'BillController@checkout')->middleware('auth')->name('bill.checkout');

//Management Route
Route::get('financereport', 'FinanceReportController@index')->middleware('auth')->name('financereport.index');
Route::get('financereport/printreport', 'FinanceReportController@printreport')->middleware('auth')->name('financereport.printreport');
Route::get('financereport/cash', 'FinanceReportDetailController@cashindex')->middleware('auth')->name('financereport.cashindex');
Route::get('financereport/debit', 'FinanceReportDetailController@debitindex')->middleware('auth')->name('financereport.debitindex');
Route::get('financereport/credit', 'FinanceReportDetailController@creditindex')->middleware('auth')->name('financereport.creditindex');
Route::get('financereport/cash/printreport', 'FinanceReportDetailController@printcashreport')->middleware('auth')->name('financereport.printcashreport');
Route::get('financereport/debit/printreport', 'FinanceReportDetailController@printdebitreport')->middleware('auth')->name('financereport.printdebitreport');
Route::get('financereport/credit/printreport', 'FinanceReportDetailController@printcreditreport')->middleware('auth')->name('financereport.printcreditreport');
Route::get('omzetreport', 'OmzetReportController@index')->middleware('auth')->name('omzetreport.index');
Route::get('omzetreport/detail/{time}', 'OmzetReportController@show')->middleware('auth')->name('omzetreport.show');
Route::get('omzetreport/printomzetreport', 'OmzetReportController@printomzetreport')->middleware('auth')->name('omzetreport.printomzetreport');
Route::get('omzetreport/detail/{time}/printreportdetail', 'OmzetReportController@printreportdetail')->middleware('auth')->name('omzetreport.printreportdetail');
Route::get('trendreport', 'TrendController@index')->middleware('auth')->name('trendreport.index');
Route::get('trendreport/{group}', 'TrendController@show')->middleware('auth')->name('trendreport.show');
Route::get('trendreport/{group}/printtrendreport', 'TrendController@printtrendreport')->middleware('auth')->name('trendreport.printtrendreport');
Route::get('customerreport', 'CustomerProfileController@index')->middleware('auth')->name('customerreport.index');
Route::get('customerreport/citysegmentreport', 'CustomerProfileController@reportcitysegment')->middleware('auth')->name('customerreport.citysegmentreport');
Route::get('customerreport/professionsegmentreport', 'CustomerProfileController@reportprofessionsegment')->middleware('auth')->name('customerreport.professionsegmentreport');
Route::get('customerreport/showgendersegment/{gender}', 'CustomerProfileDetailController@showgendersegment')->middleware('auth')->name('customerreport.showgendersegment');
Route::get('customerreport/showmaritalsegment/{marital}', 'CustomerProfileDetailController@showmaritalsegment')->middleware('auth')->name('customerreport.showmaritalsegment');
Route::get('customerreport/showagesegment/{age}', 'CustomerProfileDetailController@showagesegment')->middleware('auth')->name('customerreport.showagesegment');
Route::get('customerreport/showgendersegment/{gender}/reportgendersegment', 'CustomerProfileDetailController@reportgendersegment')->middleware('auth')->name('customerreport.reportgendersegment');
Route::get('customerreport/showmaritalsegment/{marital}/reportmaritalsegment', 'CustomerProfileDetailController@reportmaritalsegment')->middleware('auth')->name('customerreport.reportmaritalsegment');
Route::get('customerreport/showagesegment/{age}/reportagesegment', 'CustomerProfileDetailController@reportagesegment')->middleware('auth')->name('customerreport.reportagesegment');

//Upload Picture
Route::get('store/{store}', 'UploadPictureController@upload')->name('upload.picture');
Route::put('store/{store}', 'UploadPictureController@store')->name('store.picture');

app/LoyaltyProgram.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LoyaltyProgram extends Model
{
    protected $fillable = ['program_name', 'start_date', 'end_date', 'discount', 'description'];

    public function orders()
    {
        return $this->hasMany(Order::class, 'loyalty_program_id');
    }
    public function customers()
    {
        return $this->hasMany(Customer::class, 'loyalty_program_id');
    }
}

app/Http/Controllers/LoyaltyProgramController.php
<?php

namespace App\Http\Controllers;

use App\LoyaltyProgram;
use App\Http\Requests\LoyaltyProgramStore;
use Illuminate\Http\Request;

class LoyaltyProgramController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $loyaltyprograms = LoyaltyProgram::latest('updated_at')->paginate(10);
        return view('loyaltyprogram.index', ['loyaltyprograms' => $loyaltyprograms]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('loyaltyprogram.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LoyaltyProgramStore $request)
    {
        $loyaltyprogram = new LoyaltyProgram();
        $loyaltyprogram->fill($request->all());
        $loyaltyprogram->save();
        return redirect()->route('loyaltyprogram.index')->with('message', 'Data berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(LoyaltyProgram $loyaltyprogram)
    {
        return view('loyaltyprogram.view', ['loyaltyprogram' => $loyaltyprogram]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(LoyaltyProgram $loyaltyprogram)
    {
        return view('loyaltyprogram.edit', ['loyaltyprogram' => $loyaltyprogram]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(LoyaltyProgramStore $request, LoyaltyProgram $loyaltyprogram)
    {
        $loyaltyprogram->fill($request->all());
        $loyaltyprogram->save();
        return redirect()->route('loyaltyprogram.index')->with('message', 'Data berhasil diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(LoyaltyProgram $loyaltyprogram)
    {
        $loyaltyprogram->delete();
        return redirect()->route('loyaltyprogram.index')->with('message', 'Data berhasil dihapus');
    }
}

resources/views/loyaltyprogram/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Tambah Loyalty Program Baru</h3>
			@if ($errors->count() > 0)
			<div class="alert alert-danger">
				@foreach ($errors->all() as $message)
				    <li>{{ $message }}</li>
				@endforeach
			</div>
			@endif
			<form action="{{ route('loyaltyprogram.store') }}" method="post">
				
				{{ csrf_field() }}

				<div class="form-group">
					<label>Nama Program</label>
					<input type="text" name="program_name" class="form-control" value="{{ old('program_name') }}">
				</div>
				<div class="form-group">
					<label>Tanggal Mulai</label>
					<input type="date" name="start_date" class="form-control" value="{{ old('start_date') }}">
				</div>
				<div class="form-group">
					<label>Tanggal Berakhir</label>
					<input type="date" name="end_date" class="form-control" value="{{ old('end_date') }}">
				</div>
				<div class="form-group">
					<label>Diskon (%)</label>
					<input type="number" name="discount" min="0" max="100" class="form-control" value="{{ old('discount') }}">
				</div>
				<div class="form-group">
					<label>Deskripsi Program</label>
					<input type="textarea" name="description" class="form-control" value="{{ old('description') }}">
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
				<a class="btn btn-primary" href="{{ route('loyaltyprogram.index') }}" role="button">Kembali</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/loyaltyprogram/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Edit Data Loyalty Program</h3>
			<form action="{{ route('loyaltyprogram.update', $loyaltyprogram) }}" method="post">
				
				{{ csrf_field() }}
				{{ method_field('put') }}

				<div class="form-group">
					<label>Nama Program</label>
					<input type="text" name="program_name" class="form-control" value="{{ $loyaltyprogram->program_name}}">
				</div>
				<div class="form-group">
					<label>Tanggal Mulai</label>
					<input type="date" name="start_date" class="form-control" value="{{ $loyaltyprogram->start_date}}">
				</div>
				<div class="form-group">
					<label>Tanggal Berakhir</label>
					<input type="date" name="end_date" class="form-control" value="{{ $loyaltyprogram->end_date}}">
				</div>
				<div class="form-group">
					<label>Diskon (%)</label>
					<input type="number" name="discount" min="0" max="100" class="form-control" value="{{ $loyaltyprogram->discount}}">
				</div>
				<div class="form-group">
					<label>Deskripsi Program</label>
					<input type="textarea" name="description" class="form-control" value="{{ $loyaltyprogram->description}}">
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
				<a class="btn btn-primary" href="{{ route('loyaltyprogram.index') }}" role="button">Kembali</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/loyaltyprogram/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Daftar Loyalty Program</h3>
			@if(Session::has('message'))
				<div class="alert alert-success">{{ Session::get('message') }}</div>
			@endif
			<a href="{{ route('loyaltyprogram.create') }}" class="btn btn-primary">Tambah Program</a>
			<br></br>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Nomor</th>
						<th>Nama Program</th>
						<th>Tanggal Mulai</th>
						<th>Tanggal Berakhir</th>			
						<th>Diskon</th>
						<th>Aksi</th>
					</tr>
				</thead>
				<tbody>
					@forelse ($loyaltyprograms as $loyaltyprogram)
					<tr>
						<td>{{ $loyaltyprogram->id }}</td>
						<td>{{ $loyaltyprogram->program_name }}</td>
						<td>{{ date('d-m-Y', strtotime($loyaltyprogram->start_date)) }}</td>
						<td>{{ date('d-m-Y', strtotime($loyaltyprogram->end_date)) }}</td>
						<td>{{ $loyaltyprogram->discount }} %</td>
						<td>
							<a href="{{ route('loyaltyprogram.show', $loyaltyprogram->id) }}" class="btn btn-warning">View</a>
							<a href="{{ route('loyaltyprogram.edit', $loyaltyprogram->id) }}" class="btn btn-primary">Edit</a>
							<a href="{{ route('loyaltyprogram.delete', $loyaltyprogram->id) }}" class="btn btn-danger">Delete</a>
						</td>
					</tr>
					@empty
					    <td colspan="6">Belum ada data</td>
					@endforelse
				</tbody>
			</table>
			{!! $loyaltyprograms->links() !!}
		</div>
	</div>
</div>
@endsection

resources/views/loyaltyprogram/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Detail Data Loyalty Program</h3>
				<div class="form-group">
					<div class="col-lg-3 control-label">Nama Program</div>
					<div class="col-lg-9"> {{ $loyaltyprogram->program_name}} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Tanggal Mulai</div>
					<div class="col-lg-9"> {{ date('d-m-Y', strtotime($loyaltyprogram->start_date)) }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Tanggal Berakhir</div>
					<div class="col-lg-9"> {{ date('d-m-Y', strtotime($loyaltyprogram->end_date)) }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Diskon</div>
					<div class="col-lg-9"> {{ $loyaltyprogram->discount}} %</div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Deskripsi</div>
					<div class="col-lg-9"> {{ $loyaltyprogram->description}} </div>
				</div>
				<br>
				<a class="btn btn-primary" href="{{ route('loyaltyprogram.index') }}" role="button">Kembali</a>
		</div>
	</div>
</div>
@endsection