routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Admin Route
Route::resource('shopkeeper', 'ShopkeeperController')->middleware('auth');
Route::get('shopkeeper/{shopkeeper}/delete', 'ShopkeeperController@destroy')->name('shopkeeper.delete');
Route::resource('loyaltyprogram', 'LoyaltyProgramController')->middleware('auth');
Route::get('loyaltyprogram/{loyaltyprogram}/delete', 'LoyaltyProgramController@destroy')->name('loyaltyprogram.delete');
Route::resource('item', 'ItemController')->middleware('auth');
Route::get('item/{item}/delete', 'ItemController@destroy')->name('item.delete');
Route::resource('shopkeeperstatus', 'ShopkeeperStatusController')->middleware('auth');
Route::resource('customer', 'CustomerController')->middleware('auth');
Route::resource('useraccess', 'UserAccessController')->middleware('auth');
Route::resource('accesslog', 'AccessLogController')->middleware('auth');

//Staff Route
Route::resource('order', 'OrderController')->middleware('auth');
Route::get('order/{order}/delete', 'OrderController@destroy')->name('order.delete');
Route::resource('bill', 'BillController')->middleware('auth');
Route::post('printreceipt', 'BillController@checkout')->middleware('auth')->name('bill.checkout');

//Management Route
Route::get('financereport', 'FinanceReportController@index')->middleware('auth')->name('financereport.index');
Route::get('financereport/printreport', 'FinanceReportController@printreport')->middleware('auth')->name('financereport.printreport');
Route::get('financereport/cash', 'FinanceReportDetailController@cashindex')->middleware('auth')->name('financereport.cashindex');
Route::get('financereport/debit', 'FinanceReportDetailController@debitindex')->middleware('auth')->name('financereport.debitindex');
Route::get('financereport/credit', 'FinanceReportDetailController@creditindex')->middleware('auth')->name('financereport.creditindex');
Route::get('financereport/cash/printreport', 'FinanceReportDetailController@printcashreport')->middleware('auth')->name('financereport.printcashreport');
Route::get('financereport/debit/printreport', 'FinanceReportDetailController@printdebitreport')->middleware('auth')->name('financereport.printdebitreport');
Route::get('financereport/credit/printreport', 'FinanceReportDetailController@printcreditreport')->middleware('auth')->name('financereport.printcreditreport');
Route::get('omzetreport', 'OmzetReportController@index')->middleware('auth')->name('omzetreport.index');
Route::get('omzetreport/detail/{time}', 'OmzetReportController@show')->middleware('auth')->name('omzetreport.show');
Route::get('omzetreport/printomzetreport', 'OmzetReportController@printomzetreport')->middleware('auth')->name('omzetreport.printomzetreport');
Route::get('omzetreport/detail/{time}/printreportdetail', 'OmzetReportController@printreportdetail')->middleware('auth')->name('omzetreport.printreportdetail');
Route::get('trendreport', 'TrendController@index')->middleware('auth')->name('trendreport.index');
Route::get('trendreport/{group}', 'TrendController@show')->middleware('auth')->name('trendreport.show');
Route::get('trendreport/{group}/printtrendreport', 'TrendController@printtrendreport')->middleware('auth')->name('trendreport.printtrendreport');
Route::get('customerreport', 'CustomerProfileController@index')->middleware('auth')->name('customerreport.index');
Route::get('customerreport/citysegmentreport', 'CustomerProfileController@reportcitysegment')->middleware('auth')->name('customerreport.citysegmentreport');
Route::get('customerreport/professionsegmentreport', 'CustomerProfileController@reportprofessionsegment')->middleware('auth')->name('customerreport.professionsegmentreport');
Route::get('customerreport/showgendersegment/{gender}', 'CustomerProfileDetailController@showgendersegment')->middleware('auth')->name('customerreport.showgendersegment');
Route::get('customerreport/showmaritalsegment/{marital}', 'CustomerProfileDetailController@showmaritalsegment')->middleware('auth')->name('customerreport.showmaritalsegment');
Route::get('customerreport/showagesegment/{age}', 'CustomerProfileDetailController@showagesegment')->middleware('auth')->name('customerreport.showagesegment');
Route::get('customerreport/showgendersegment/{gender}/reportgendersegment', 'CustomerProfileDetailController@reportgendersegment')->middleware('auth')->name('customerreport.reportgendersegment');
Route::get('customerreport/showmaritalsegment/{marital}/reportmaritalsegment', 'CustomerProfileDetailController@reportmaritalsegment')->middleware('auth')->name('customerreport.reportmaritalsegment');
Route::get('customerreport/showagesegment/{age}/reportagesegment', 'CustomerProfileDetailController@reportagesegment')->middleware('auth')->name('customerreport.reportagesegment');

//Upload Picture
Route::get('store/{store}', 'UploadPictureController@upload')->name('upload.picture');
Route::put('store/{store}', 'UploadPictureController@store')->name('store.picture');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Customer extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    
    public function user() 
    {
    	return $this->belongsTo(User::class, 'user_id');
    }
    public function loyaltyprogram() 
    {
    	return $this->belongsTo(LoyaltyProgram::class, 'loyalty_program_id');
    }
    public function orders()
    {
        return $this->hasMany(Order::class, 'customer_id');
    }
    public function bills()
    {
        return $this->hasMany(Bill::class, 'customer_id');
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::latest('updated_at')->paginate(10);
        return view('customer.index', ['customers' => $customers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        return view('customer.view', ['customer' => $customer]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col">
			<h3>Daftar Pelanggan</h3>
			@if(Session::has('message'))
				<div class="alert alert-success">{{ Session::get('message') }}</div>
			@endif
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Nomor</th>
						<th>Nama Customer</th>
						<th>Usia</th>
						<th>Pekerjaan</th>
						<th>Email</th>
						<th>Nomor Telepon</th>			
						<th>Aksi</th>
					</tr>
				</thead>
				<tbody>
					@forelse ($customers as $customer)
					<tr>
						<td>{{ $customer->id }}</td>
						<td>{{ $customer->customer_name }}</td>
						<td>{{ $customer->age }}</td>
						<td>{{ $customer->profession }}</td>
						<td>{{ $customer->email }}</td>
						<td>{{ $customer->phone_number }}</td>
						<td>
							<a href="{{ route('customer.show', $customer->id) }}" class="btn btn-warning">View</a>
						</td>
					</tr>
					@empty
					    <td colspan="7">Belum ada data</td>
					@endforelse
				</tbody>
			</table>
			{!! $customers->links() !!}
		</div>
	</div>
</div>
@endsection

resources/views/customer/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Detail Data Pelanggan</h3>
				<div class="form-group">
					<div class="col-lg-3 control-label">Nama Customer</div>
					<div class="col-lg-9"> {{ $customer->customer_name }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Tanggal Lahir</div>
					<div class="col-lg-9"> {{ date('d-m-Y', strtotime($customer->birth_date)) }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Umur</div>
					<div class="col-lg-9"> {{ $customer->age }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Gender</div>
					<div class="col-lg-9"> {{ $customer->gender }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Pekerjaan</div>
					<div class="col-lg-9"> {{ $customer->profession }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Status Pernikahan</div>
					<div class="col-lg-9"> {{ $customer->marital_status }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Email</div>
					<div class="col-lg-9"> {{ $customer->email }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Alamat</div>
					<div class="col-lg-9"> {{ $customer->address }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Kota</div>
					<div class="col-lg-9"> {{ $customer->city }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">Nomor Telepon</div>
					<div class="col-lg-9"> {{ $customer->phone_number }} </div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 control-label">QR Code</div>
					<div class="col-lg-9"> <img src="{{ asset($customer->QR_Code) }}" alt="No QR Code"></div>
				</div>
				<br>
				<a class="btn btn-primary" href="{{ route('customer.index') }}" role="button">Kembali</a>
		</div>
	</div>
</div>
@endsection