routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Admin Route
Route::resource('shopkeeper', 'ShopkeeperController')->middleware('auth');
Route::get('shopkeeper/{shopkeeper}/delete', 'ShopkeeperController@destroy')->name('shopkeeper.delete');
Route::resource('loyaltyprogram', 'LoyaltyProgramController')->middleware('auth');
Route::get('loyaltyprogram/{loyaltyprogram}/delete', 'LoyaltyProgramController@destroy')->name('loyaltyprogram.delete');
Route::resource('item', 'ItemController')->middleware('auth');
Route::get('item/{item}/delete', 'ItemController@destroy')->name('item.delete');
Route::resource('shopkeeperstatus', 'ShopkeeperStatusController')->middleware('auth');
Route::resource('customer', 'CustomerController')->middleware('auth');
Route::resource('useraccess', 'UserAccessController')->middleware('auth');
Route::resource('accesslog', 'AccessLogController')->middleware('auth');

//Staff Route
Route::resource('order', 'OrderController')->middleware('auth');
Route::get('order/{order}/delete', 'OrderController@destroy')->name('order.delete');
Route::resource('bill', 'BillController')->middleware('auth');
Route::post('printreceipt', 'BillController@checkout')->middleware('auth')->name('bill.checkout');

//Management Route
Route::get('financereport', 'FinanceReportController@index')->middleware('auth')->name('financereport.index');
Route::get('financereport/printreport', 'FinanceReportController@printreport')->middleware('auth')->name('financereport.printreport');
Route::get('financereport/cash', 'FinanceReportDetailController@cashindex')->middleware('auth')->name('financereport.cashindex');
Route::get('financereport/debit', 'FinanceReportDetailController@debitindex')->middleware('auth')->name('financereport.debitindex');
Route::get('financereport/credit', 'FinanceReportDetailController@creditindex')->middleware('auth')->name('financereport.creditindex');
Route::get('financereport/cash/printreport', 'FinanceReportDetailController@printcashreport')->middleware('auth')->name('financereport.printcashreport');
Route::get('financereport/debit/printreport', 'FinanceReportDetailController@printdebitreport')->middleware('auth')->name('financereport.printdebitreport');
Route::get('financereport/credit/printreport', 'FinanceReportDetailController@printcreditreport')->middleware('auth')->name('financereport.printcreditreport');
Route::get('omzetreport', 'OmzetReportController@index')->middleware('auth')->name('omzetreport.index');
Route::get('omzetreport/detail/{time}', 'OmzetReportController@show')->middleware('auth')->name('omzetreport.show');
Route::get('omzetreport/printomzetreport', 'OmzetReportController@printomzetreport')->middleware('auth')->name('omzetreport.printomzetreport');
Route::get('omzetreport/detail/{time}/printreportdetail', 'OmzetReportController@printreportdetail')->middleware('auth')->name('omzetreport.printreportdetail');
Route::get('trendreport', 'TrendController@index')->middleware('auth')->name('trendreport.index');
Route::get('trendreport/{group}', 'TrendController@show')->middleware('auth')->name('trendreport.show');
Route::get('trendreport/{group}/printtrendreport', 'TrendController@printtrendreport')->middleware('auth')->name('trendreport.printtrendreport');
Route::get('customerreport', 'CustomerProfileController@index')->middleware('auth')->name('customerreport.index');
Route::get('customerreport/citysegmentreport', 'CustomerProfileController@reportcitysegment')->middleware('auth')->name('customerreport.citysegmentreport');
Route::get('customerreport/professionsegmentreport', 'CustomerProfileController@reportprofessionsegment')->middleware('auth')->name('customerreport.professionsegmentreport');
Route::get('customerreport/showgendersegment/{gender}', 'CustomerProfileDetailController@showgendersegment')->middleware('auth')->name('customerreport.showgendersegment');
Route::get('customerreport/showmaritalsegment/{marital}', 'CustomerProfileDetailController@showmaritalsegment')->middleware('auth')->name('customerreport.showmaritalsegment');
Route::get('customerreport/showagesegment/{age}', 'CustomerProfileDetailController@showagesegment')->middleware('auth')->name('customerreport.showagesegment');
Route::get('customerreport/showgendersegment/{gender}/reportgendersegment', 'CustomerProfileDetailController@reportgendersegment')->middleware('auth')->name('customerreport.reportgendersegment');
Route::get('customerreport/showmaritalsegment/{marital}/reportmaritalsegment', 'CustomerProfileDetailController@reportmaritalsegment')->middleware('auth')->name('customerreport.reportmaritalsegment');
Route::get('customerreport/showagesegment/{age}/reportagesegment', 'CustomerProfileDetailController@reportagesegment')->middleware('auth')->name('customerreport.reportagesegment');

//Upload Picture
Route::get('store/{store}', 'UploadPictureController@upload')->name('upload.picture');
Route::put('store/{store}', 'UploadPictureController@store')->name('store.picture');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function customer() 
    {
    	return $this->belongsTo(Customer::class, 'customer_id');
    }
    public function item() 
    {
    	return $this->belongsTo(Item::class, 'item_id');
    }
    public function items() 
    {
        return $this->hasOne(Item::class, 'id', 'item_id');
    }      
    public function loyaltyprogram() 
    {
    	return $this->belongsTo(LoyaltyProgram::class, 'loyalty_program_id');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Validator;
use App\Customer;
use App\Item;
use App\Order;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class OrderController extends Controller
{
    public function index(Request $request)
    {
        if (isset($request->customer_id)) {
            $orders = Order::get()->where('status', 'PROCESS')->where('customer_id', $request->customer_id);
        } else {
            $orders = Order::get()->where('status' , 'PROCESS');
        }
        $customers = Customer::get();
        return view('order.index', ['orders' => $orders, 'customers' => $customers]);
    }
    public function create() 
    {
    	$items = Item::get();
    	$customers = Customer::get();
    	return view('order.create', ['items' => $items, 'customers' => $customers]);
    }
    public function store(Request $request)
    {
    	$items = Item::get();
    	$itemarray = array();
    	foreach ($items as $item) {
    		array_push($itemarray, $item->item_name);
    	}
    	$customers = Customer::get();
    	$customerarray = array();
    	foreach ($customers as $customer) {
    		array_push($customerarray, $customer->customer_name);
    	}
        $rules = [
        	'customer_name' => 'required|in:' . implode(',', $customerarray),
            'item_name' => 'required|in:' . implode(',', $itemarray),
            'quantity' => 'required|numeric',
        ];
        $messages = [
            'item_name.required' => 'Nama Barang harus diisi',
            'item_name.in' => 'Nama Barang tidak ada dalam daftar',
            'customer_name.required' => 'Nama Customer harus diisi',
            'customer_name.in' => 'Nama Customer tidak ada dalam daftar',
            'quantity.required' => 'Jumlah Barang harus diisi',
            'quantity.numeric' => 'Jumlah Barang harus berupa angka',
        ];
        Validator::make($request->all(), $rules, $messages)->validate();
        $order = new Order();
        $item = Item::where('item_name', $request->item_name)->first();
        $customer = Customer::where('customer_name', $request->customer_name)->first();       
        $order->customer_id = $customer->id;
        $order->item_id = $item->id;
        $order->loyalty_program_id = $customer->loyalty_program_id;
        $order->quantity = $request->quantity;
        $order->subtotal = ($item->price * $order->quantity) - ($item->price * $order->quantity * ($customer->loyaltyprogram->discount / 100));
        $order->status = "PROCESS";
        $item->stock = $item->stock - $request->quantity;
        if ($item->stock < 0) {
            return redirect()->route('order.index')->with('message', 'Stok Barang Telah Habis/Kurang Cukup');
        } else {
            $order->save();
            $item->save();
            return redirect()->route('order.index')->with('message', 'Data berhasil ditambahkan');
        }
    }
    public function show(Order $order)
    {

    }
    public function edit(Order $order)
    {
    	$items = Item::get();
    	$itemorder = Item::where('id', $order->item_id)->first();
		return view('order.edit', ['order' => $order, 'items' => $items, 'itemorder' => $itemorder]);
    }
    public function update(Request $request, Order $order)
    {
    	$items = Item::get();
    	$itemarray = array();
    	foreach ($items as $item) {
    		array_push($itemarray, $item->item_name);
    	}
    	//dd($itemarray);
        $rules = [
            'item_name' => 'required|in:' . implode(',', $itemarray),
            'quantity' => 'required|numeric',
        ];
        $messages = [
            'item_name.required' => 'Nama Barang harus diisi',
            'item_name.in' => 'Nama Barang tidak ada dalam daftar',
            'quantity.required' => 'Jumlah Barang harus diisi',
            'quantity.numeric' => 'Jumlah Barang harus berupa angka',
        ];
        Validator::make($request->all(), $rules, $messages)->validate();
        $item = Item::where('item_name', $request->item_name)->first();
        $item->stock = $item->stock + $order->quantity;     
        $order->item_id = $item->id;
        $order->quantity = $request->quantity;
        $order->subtotal = ($item->price * $order->quantity) - ($item->price * $order->quantity * ($order->loyaltyprogram->discount / 100));
        $item->stock = $item->stock - $request->quantity;
        if ($item->stock < 0) {
            return redirect()->route('order.index')->with('message', 'Stok Barang Telah Habis/Kurang Cukup');
        } else {
            $order->save();
            $item->save();
            return redirect()->route('order.index')->with('message', 'Data berhasil diedit');
        }
    }
    public function destroy(Order $order)
    {
        $order->delete();
        return redirect()->route('order.index')->with('message', 'Data berhasil dihapus');
    }
}

resources/views/order/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Tambah Order</h3>
			@if ($errors->count() > 0)
			<div class="alert alert-danger">
				@foreach ($errors->all() as $message)
				    <li>{{ $message }}</li>
				@endforeach
			</div>
			@endif
			<form action="{{ route('order.store') }}" method="post">
				
				{{ csrf_field() }}

				<div class="form-group">
					<label>Nama Customer</label>
					  <select name="customer_name" class="form-control">
					  	@foreach ($customers as $customer)
					    <option value="{{ $customer->customer_name }}"> {{ $customer->customer_name }} </option>
					    @endforeach
					  </select>
				</div>
				<div class="form-group">
					<label>Nama Barang</label>
					<input list="item_name" name="item_name" class="form-control">
					  <datalist id="item_name">
					  	@foreach ($items as $item)
					    <option value="{{ $item->item_name }}"> 
					    @endforeach
					  </datalist>
				</div>
				<div class="form-group">
					<label>Jumlah</label>
					<input type="text" name="quantity" class="form-control" value="{{ old('quantity') }}">
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
				<a class="btn btn-primary" href="{{ route('order.index') }}" role="button">Kembali</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/order/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Edit Data Order</h3>
			<form action="{{ route('order.update', $order->id) }}" method="post">
				
				{{ csrf_field() }}
				{{ method_field('put') }}

				<div class="form-group">
					<label>Nama Barang</label>
					<input list="item_name" name="item_name" class="form-control" value="{{ $itemorder->item_name }}">
					  <datalist id="item_name">
					  	@foreach ($items as $item)
					    <option value="{{ $item->item_name }}"> 
					    @endforeach
					  </datalist>
				</div>
				<div class="form-group">
					<label>Jumlah</label>
					<input type="text" name="quantity" class="form-control" value="{{ $order->quantity }}">
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
				<a class="btn btn-primary" href="{{ route('order.index') }}" role="button">Kembali</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<h3>Entri Order</h3>
			@if(Session::has('message'))
				<div class="alert alert-success">{{ Session::get('message') }}</div>
			@endif
			<a href="{{ route('order.create') }}" class="btn btn-primary">Tambah Order</a>
			<br></br>
			<form action="{{ route('order.index') }}" method="POST">
					{{ csrf_field() }}
					{{ method_field('GET') }}
					<div class="form-group">
							<label>Customer</label>
							<select class="form-control" name="customer_id" onchange="this.form.submit()">
								<option value="none" selected disabled>Pilih Customer</option>
						    	@foreach($customers as $customer)
						    		<option value="{{ $customer->id }}">{{ $customer->customer_name }}</option>
						    	@endforeach
							</select>
					</div>    
			</form>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Nomor</th>
						<th>Nama Barang</th>
						<th>Satuan</th>
						<th>Harga</th>
						<th>Diskon</th>			
						<th>Subtotal</th>
						<th>Aksi</th>
					</tr>
				</thead>
				<tbody>
					@php
					$total = 0;
					$nomor = 1;
					@endphp
					@forelse ($orders as $order)
					@php
					$total = $total + $order->subtotal;
					@endphp
					<tr>
						<td>{{ $nomor }}</td>
						<td>{{ $order->item->item_name }}</td>
						<td>{{ $order->quantity }}</td>
						<td>Rp {{ number_format($order->item->price, 2, ',', '.') }}</td>
						<td>{{ $order->loyaltyprogram->discount }} %</td>
						<td>Rp {{ number_format($order->subtotal, 2, ',', '.') }}</td>
						<td>
							<a href="{{ route('order.edit', $order->id) }}" class="btn btn-primary">Edit</a>
							<a href="{{ route('order.delete', $order->id) }}" class="btn btn-danger">Delete</a>
						</td>
					</tr>
					@php
					$nomor = $nomor + 1;
					@endphp
					@empty
					    <td colspan="7">Belum ada data</td>
					@endforelse
					<tr>
						<td colspan="5"><b>Total</b></td>
						<td><b>Rp {{ number_format($total, 2, ',', '.') }}</b></td>
						<td>
							<a href="{{ route('bill.index') }}" class="btn btn-warning">Checkout</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col">
			
		</div>
	</div>
</div>
@endsection